### ISSUE TITLE
react - springboot 연동오류

### ISSUE THREAD

**Issue by devdynam0507** [InoFlexin/meta-class#1]
gradle빌드시 react yarn 실행하는 시점에서 에러가 뜨는 이슈

**Comment by kebin0613** [comment]
master 처음에 clone시 npm start, yarn start 에러시 아래 3개의 명령어 수행
npm install --save-dev react-dev-utils
npm update
yarn update

위의 3개의 명령어 수행시에도 안될 시 아래 명령어 수행
npm install -g react-scripts

**Comment by devdynam0507** [comment]
yarn이 설치되지 않아서 뜨는 오류인가요?

**Comment by kebin0613** [comment]
@devdynam0507  
설치되어있는 상태에서도 오류가 발생합니다.
그래서 처음부터 버전을 맞춘후 react-scrpts를 글로벌로 설치하니 해결되었습니다.
package.json 보니 그렇더군요! 설정하시느라 고생하셨습니다  <hr>(번역체ㅋㅋ)<hr>

**Comment by devdynam0507** [comment]
@kebin0613 
고생하셨습니다.
이건 다른 개발자도 볼 수 있게 레퍼런스로 남겨주세요!
